all: clean inheritance virtual constructorSequence singleton

CPP_ARGS = -g -Wall

inheritance:
	g++ -o inheritance inheritance.cpp $(CPP_ARGS)

virtual:
	g++ -o virtual virtual.cpp $(CPP_ARGS)

constructorSequence:
	g++ -o constructorSequence constructorSequence.cpp $(CPP_ARGS)

singleton:
	g++ -o singleton singleton.cpp $(CPP_ARGS)

clean:
	-rm inheritance virtual constructorSequence singleton
